pipeline:
  name: Dckrppln
  identifier: Dckrppln
  projectIdentifier: Harness1
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: newgit
        build: <+input>
  stages:
    - stage:
        name: ECRB
        identifier: ECRB
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: ecrtry
                    configuration:
                      stackName: ecrtry
                      connectorRef: AWSN
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - Ecrdemo.yml
                              connectorRef: newgit
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                      parameterOverrides:
                        - name: RepositoryName
                          value: <+input>
                          type: String
                  timeout: 10m
        tags: {}
