pipeline:
  name: eks-dckr
  identifier: eksdckr
  projectIdentifier: Harness1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: EKS-infra
        identifier: EKSinfra
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: eks
                    configuration:
                      stackName: Second-eks
                      connectorRef: AWSN
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - eksnew.yml
                              connectorRef: newgit
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                      parameterOverrides:
                        - name: ClusterName
                          value: <+input>
                          type: String
                        - name: SecurityGroup
                          value: <+input>
                          type: String
                        - name: SubnetId2
                          value: <+input>
                          type: String
                        - name: SubnetId1
                          value: <+input>
                          type: String
                  timeout: 10m
        tags: {}
