pipeline:
  name: EKS-try
  identifier: EKStry
  projectIdentifier: Harness1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Dev
        identifier: Dev
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: EKSdckr
          environment:
            environmentRef: eksuseast2
            environmentInputs:
              identifier: eksuseast2
              type: PreProduction
              variables:
                - name: subnetid1
                  type: String
                  value: <+input>
            deployToAll: false
            infrastructureDefinitions:
              - identifier: eksinfra
                inputs:
                  identifier: eksinfra
                  type: KubernetesAws
                  spec:
                    cluster: <+input>
                    namespace: <+input>
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: eks
                    configuration:
                      stackName: eks-try
                      connectorRef: AWSN
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - eksnew.yml
                              connectorRef: newgit
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                      parameterOverrides:
                        - name: ClusterName
                          value: <+input>
                          type: String
                        - name: SecurityGroup
                          value: <+input>
                          type: String
                        - name: SubnetId2
                          value: <+input>
                          type: String
                        - name: SubnetId1
                          value: <+env.variables.subnetid1>
                          type: String
                  timeout: 20m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
