pipeline:
  name: PPL
  identifier: PPL
  projectIdentifier: Harness1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Cstage
        identifier: Cstage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack
                  identifier: CreateStack
                  spec:
                    provisionerIdentifier: ABC
                    configuration:
                      stackName: firststack
                      connectorRef: AWSN
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - lab1.1.1.yaml
                              connectorRef: newgit
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                  timeout: 10m
        tags: {}
