pipeline:
  name: PPL
  identifier: PPL
  projectIdentifier: Harness1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Cstage
        identifier: Cstage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack
                  identifier: CreateStack
                  spec:
                    provisionerIdentifier: ABC
                    configuration:
                      stackName: stackcreation
                      connectorRef: AWSN
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - new.yml
                              connectorRef: newgit
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                      parameterOverrides:
                        - name: BucketName
                          value: <+pipeline.variables.BucketName>
                          type: String
                  timeout: 10m
        tags: {}
  variables:
    - name: BucketName
      type: String
      description: Enter the Bucketname
      required: false
      value: <+input>
