AWSTemplateFormatVersion: "2010-09-09"
Description: "ECRTemplatecreating"
Parameters:
  RepositoryName: 
    Default :  ' '
    Type: String
Resources:
  MyECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
Outputs:
  RepositoryName: 
    Value: !Ref RepositoryName